import {scale} from 'react-native-size-matters';
import {Dimensions} from 'react-native';

// Declaring constants
export const POPPINS_BOLD = 'Poppins-Bold';
export const POPPINS_MEDIUM = 'Poppins-Medium';
export const POPPINS_REGULAR = 'Poppins-Regular';
export const POPPINS_SEMIBOLD = 'Poppins-SemiBold';
export const FONT_SIZE_XXS = scale(10);
export const FONT_SIZE_XS = scale(12);
export const FONT_SIZE_SM = scale(14);
export const FONT_SIZE_MD = scale(16);
export const FONT_SIZE_LG = scale(20);
export const FONT_SIZE_XL = scale(24);

export const SCREEN_WIDTH = Dimensions.get('window').width;
export const SCREEN_HEIGHT = Dimensions.get('window').height;

export const STANDARD_LOGO_WIDTH = scale(177.5);
export const STANDARD_LOGO_HEIGHT = scale(217.5);
export const STANDARD_COUPON_HEIGHT = scale(200);
export const STANDARD_FLEX = 1;
export const STANDARD_Z_INDEX = 1;
export const STANDARD_SPACING = scale(5);
export const STANDARD_CHECKBOX_SIZE = scale(30);
export const STANDARD_BORDER_RADIUS = scale(5);
export const STANDARD_BORDER_WIDTH = scale(1);
export const STANDARD_BADGE_PILL_WIDTH = scale(75);
export const STANDARD_BUTTON_HEIGHT = scale(45);
export const STANDARD_NAVIGATION_LINK_HEIGHT = scale(50);
export const STANDARD_NAVIGATION_LINK_LEFT_ICON_WRAPPER_SIZE = scale(35);
export const STANDARD_TEXT_INPUT_HEIGHT = scale(45);
export const STANDARD_TEXTAREA_HEIGHT = scale(90);
export const STANDARD_SELECT_DROPDOWN_HEIGHT = scale(45);
export const STANDARD_VECTOR_ICON_WRAPPER_SIZE = scale(35);
export const STANDARD_VECTOR_ICON_SIZE = scale(20);
export const STANDARD_USER_AVATAR_WRAPPER_SIZE = scale(40);
export const STANDARD_USER_AVATAR_BADGE_WRAPPER_SIZE = scale(15);
export const STANDARD_SOCIAL_ICON_SIZE = scale(40);
export const STANDARD_LANGUAGE_RADIO_WRAPPER_HEIGHT = scale(60);
export const STANDARD_LANGUAGE_RADIO_CHECKBOX_SIZE = scale(15);
export const STANDARD_PRODUCT_CARD_SIZE = scale(110);
export const STANDARD_PRODUCT_IMAGE_WRAPPER_SIZE = scale(75);
export const STANDARD_DIVIDER_LINE_HEIGHT = scale(1);
export const STANDARD_LANGUAGE_CARD_HEIGHT = scale(60);
export const STANDARD_LANGUAGE_FLAG_SIZE = scale(30);
export const STANDARD_PAYMENT_METHOD_CARD_HEIGHT = scale(60);
export const STANDARD_LOTTIE_FILE_SIZE = scale(125);
export const STANDARD_OTP_TEXT_VIEW_SIZE = scale(40);
export const STANDARD_OTP_TEXT_VIEW_BORDER_SIZE = scale(1);
export const STANDARD_BRAND_LOGO_WRAPPER_SIZE = scale(55);
export const STANDARD_ON_BOARDING_IMAGE_SIZE = scale(250);
export const STANDARD_ON_BOARDING_PAGINATION_DOT_HEIGHT = scale(6);
export const STANDARD_WALLET_CARD_HEIGHT = scale(175);
export const STANDARD_WALLET_BILL_AND_RECHARGE_ICON_SIZE = scale(60);
export const STANDARD_WALLET_TRANSACTION_DATE_SIZE = scale(40);
export const STANDARD_DRAWER_WIDTH = scale(260);
export const STANDARD_DRAWER_HEADER_HEIGHT = scale(140);
